name: netspace
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  appwrite: ^19.0.0
  cloud_firestore: ^6.0.1
  firebase_ai: ^3.2.0
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  firebase_database: ^12.0.1
  firebase_in_app_messaging: ^0.9.0+1
  firebase_messaging: ^16.0.1
  firebase_storage: ^13.0.1
  flutter:
    sdk: flutter
  google_fonts: ^6.3.1
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
